### ISSUE TITLE
Not overwriting top-level child i.e. --append

### ISSUE THREAD

**Issue by stalane** [firebase/firebase-import#25]
Can we have an option to --append that doesn't overwrite the top-level child?

**Comment by mikelehen** [comment]
There's a --merge already...  Does that do what you need? :-)

**Comment by stalane** [comment]
Hi there Mike. No the --merge option overwrites the top-level child. Here is my firebase:

![structure](https://cloud.githubusercontent.com/assets/4401195/23341938/d99f4b7a-fc8b-11e6-96c8-3d09866f41bd.png)

I would like to be able to import and append records under the top-level children i.e. events,geo,log,users

**Comment by mikelehen** [comment]
Can you give an example of the json you're trying to import and the command-line you're using?

**Comment by stalane** [comment]
{
  "events": {
    "-KKQQIUR7FAVxBOPOFhr": {
      "dateAdded": 1487592568926,
      "owner": "62e6aaa0-a50c-4448-a381-f02efde2316d",
      "type": "boycott"
    }
  },
  "geo": {
    "-KKQQIUR7FAVxBOPOFhr": {
      ".priority": "qw3yttz1k9",
      "g": "qw3yttz1k9",
      "l": [
        41.5825024,
        -73.7622713
      ]
    }
  },
  "log": "null",
  "users": {
    "62e6aaa0-a50c-4448-a381-f02efde2316d" : {
      "events" : {
        "-KKQQIUR7FAVxBOPOFhr" : {
          "type" : "boycott"
        }
      }
    }
  }
}

**Comment by stalane** [comment]
firebase-import --service_account my-service.json --database_url https://my.firebaseio.com --path / --json import.json --merge

**Comment by mikelehen** [comment]
I see...   Looks like you're trying to append to 3 different paths (/events, /geo, and /users) at once (not sure what the expected behavior of "log" is since it is null instead of having children to append).  

Unfortunately that's not supported, sorry.  firebase-import lets you completely overwrite a location or with --merge, merge the top-level children in at that location.  You're trying to do a "merge" of the children of the top-level-children. :-)

You could do this with 3 separate firebase-import calls (one to append to "events", one to append to "geo", one to append to "users"), which should be pretty straightforward if this is just a one-time import (the primary use case for firebase-import).

If you're trying to use firebase-import for some sort of recurring data importing, you're probably better off using the REST API or one of the client SDKs.  For info on doing atomic writes to multiple locations across your Firebase, see [here](https://firebase.googleblog.com/2015/09/introducing-multi-location-updates-and_86.html).

FWIW, I don't think an --append option would be the right approach.  --merge already dose a merge one-level deep (i.e. it would overwrite "/events", "/geo", and "/users" but wouldn't overwrite any other existing top-level children, e.g. "/users").  It looks like you want to do a merge 2 levels deep.  So we'd need an arbitrary "--merge <depth>" option or something.

**Comment by stalane** [comment]
Grandkids eh? What can you do.... :/

I tried 3 separate firebase-import calls but the result was the same, which wasnt surprising, because I just split the file into 3 parts.

This would be a one-time import (mostly) use case. I will have a look at trying to merge the exported json file with another that has the data to be imported and then import the bigger file but json is a bugger for that kind of thing. 

Can you please add export to, and import from, csv to your already huge workload? That would be a hugely helpful feature. 

Thanks a lot for the fast help. You can close this issue :+1:

**Comment by mikelehen** [comment]
To do it with 3 separate imports you'd need to e.g. create an events.json with the events moved to the top-level, e.g. `{ "-KKQQIUR7FAVXBOPOFhr": { ... }, ... }`

And then do an import with path /events, e.g.: `firebase-import --service_account my-service.json --database_url https://my.firebaseio.com/ --path /events --json events.json --merge`

I'll keep CSV in mind.  Pull Requests are always welcome as well. :-)

**Comment by stalane** [comment]
oic. This now works just fine. Thanks again Mike.
