### ISSUE TITLE
Does this work with the new Firestore DB?

### ISSUE THREAD

**Issue by stubborncoder** [firebase/firebase-import#31]
Planing to move my no-sql db from mongolab to Firestore, and how to import the data and found this utility and I wonder if this works with firestore.

**Comment by mikelehen** [comment]
Good question!  It is only for the Firebase Realtime Database. I've updated the README to make that clearer.

Importing into Cloud Firestore should be a bit more straightforward since it uses a data model of collections containing documents already. Unfortunately you will probably have to write your own script to do it for now.
