### ISSUE TITLE
Not working behind a proxy

### ISSUE THREAD

**Issue by hemgui** [firebase/firebase-import#6]
I cannot use firebase-import behind a proxy.
I have try to set environment variable HTTP_PROXY but it don't change anything.

Is there any workaround ?

Thanks

**Comment by mikelehen** [comment]
Sorry.  There isn't any sane workaround right now (you could probably monkey patch the websocket library we depend on, faye-websocket, to force your proxy settings or something, but that's pretty extreme).

We're hoping to release a version of the firebase client that supports proxy configuration in the next few weeks, at which point firebase-import would work with proxies as well.

**Comment by rileylark** [comment]
@mikelehen Did you release a firebase client that supports proxy configuration? We have customers behind firewalls and the web client is being blocked

**Comment by mikelehen** [comment]
@rileylark Unfortunately we have not.  However I'm not sure that'll help your customers.  The web client should work fine behind proxies, since the browser takes care of that.  It's only the node client that needs extra work.  If your web users are having issues, you'll probably want to contact support@firebase.com.

**Comment by rileylark** [comment]
I want to manually proxy firebase from the browser, because many of my customer's firewalls are suddenly blocking it (some popular filter just got updated maybe?).

So instead of just saying "NOPE DOESNT WORK" I'd like to proxy their initial requests through a server with a custom domain and then later follow up with them with something like "Hey, you're blocking Firebase, and we need you to unblock it."

**Comment by mikelehen** [comment]
@rileylark Thanks.  I just replied to your support request.  But unfortunately proxying the traffic won't be straightforward.

**Comment by glauberramos** [comment]
Hello @rileylark, I am also having some clients behind firewall that is blocking firebase. Did you figure out a way to fix that?

**Comment by mikelehen** [comment]
Have you tried using the HTTPS_PROXY or HTTP_PROXY environment variable?  The Firebase SDK should respect it now I believe.

**Comment by glauberramos** [comment]
Thanks @mikelehen, I am actually not using a proxy. What is happening is that some of my customers firewall is blocking websockets from firebase. I am not sure what can I do to avoid that. Do you have any idea? Thanks

**Comment by mikelehen** [comment]
@glauberramos That sounds like a very unrelated issue then, but perhaps https://stackoverflow.com/questions/20805467/firebase-is-there-a-flag-to-force-long-polling-when-websockets-are-blocked-by will help. :-)

**Comment by glauberramos** [comment]
Thanks @hemgui
